version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: demo
      MYSQL_USER: riya
      MYSQL_PASSWORD: password123

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    networks:
      - app-network

  backend:
    build:
      context: ./backend

    container_name: springboot-app

    restart: always

    depends_on:
      - mysql

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/demo
      SPRING_DATASOURCE_USERNAME: riya
      SPRING_DATASOURCE_PASSWORD: password123

    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/my-angular-app

    container_name: angular-app

    restart: always

    depends_on:
      - backend

    ports:
      - "80:80"

    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network: